package Entities;
// Generated 18-nov-2012 18:39:09 by Hibernate Tools 3.2.1.GA



/**
 * Costumer generated by hbm2java
 */
public class Costumer  implements java.io.Serializable {


     private Integer id;
     private String name;

    public Costumer() {
    }

    public Costumer(String name) {
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


