package Entities;
// Generated 18-nov-2012 18:39:09 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Expense generated by hbm2java
 */
public class Expense  implements java.io.Serializable {


     private Integer id;
     private Date date;
     private String supplier;
     private double total;
     private String description;

    public Expense() {
    }

    public Expense(Date date, String supplier, double total, String description) {
       this.date = date;
       this.supplier = supplier;
       this.total = total;
       this.description = description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(String supplier) {
        this.supplier = supplier;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
    
}


