package Entities;
// Generated 18-nov-2012 18:39:09 by Hibernate Tools 3.2.1.GA



/**
 * FinalProductToppingsId generated by hbm2java
 */
public class FinalProductToppingsId  implements java.io.Serializable {


     private int finalProductId;
     private int toppingId;

    public FinalProductToppingsId() {
    }

    public FinalProductToppingsId(int finalProductId, int toppingId) {
       this.finalProductId = finalProductId;
       this.toppingId = toppingId;
    }
   
    public int getFinalProductId() {
        return this.finalProductId;
    }
    
    public void setFinalProductId(int finalProductId) {
        this.finalProductId = finalProductId;
    }
    public int getToppingId() {
        return this.toppingId;
    }
    
    public void setToppingId(int toppingId) {
        this.toppingId = toppingId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FinalProductToppingsId) ) return false;
		 FinalProductToppingsId castOther = ( FinalProductToppingsId ) other; 
         
		 return (this.getFinalProductId()==castOther.getFinalProductId())
 && (this.getToppingId()==castOther.getToppingId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFinalProductId();
         result = 37 * result + this.getToppingId();
         return result;
   }   


}


