package Entities;
// Generated 18-nov-2012 18:39:09 by Hibernate Tools 3.2.1.GA



/**
 * FinalProduct generated by hbm2java
 */
public class FinalProduct  implements java.io.Serializable {


     private Integer id;
     private int baseProduct;
     private double price;

    public FinalProduct() {
        this.id = 0;
        this.baseProduct = 0;
        this.price = 0;
    }

    public FinalProduct(int baseProduct, double price) {
       this.baseProduct = baseProduct;
       this.price = price;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getBaseProduct() {
        return this.baseProduct;
    }
    
    public void setBaseProduct(int baseProduct) {
        this.baseProduct = baseProduct;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }




}


