package Entities;
// Generated 18-nov-2012 18:39:09 by Hibernate Tools 3.2.1.GA



/**
 * FinalProductToppings generated by hbm2java
 */
public class FinalProductToppings  implements java.io.Serializable {


     private FinalProductToppingsId id;

    public FinalProductToppings() {
        this.id = null;
    }

    public FinalProductToppings(FinalProductToppingsId id) {
       this.id = id;
    }
   
    public FinalProductToppingsId getId() {
        return this.id;
    }
    
    public void setId(FinalProductToppingsId id) {
        this.id = id;
    }

}


