package Entities;
// Generated 18-nov-2012 18:39:09 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Sale generated by hbm2java
 */
public class Sale  implements java.io.Serializable {


     private Integer id;
     private Date date;
     private int finalProductId;
     private double price;
     private int customerId;
     private double total;

    public Sale() {
    }

    public Sale(Date date, int finalProduct, double price, int client, double total) {
       this.date = date;
       this.finalProductId = finalProduct;
       this.price = price;
       this.customerId = client;
       this.total = total;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public int getFinalProduct() {
        return this.finalProductId;
    }
    
    public void setFinalProduct(int finalProduct) {
        this.finalProductId = finalProduct;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public int getClient() {
        return this.customerId;
    }
    
    public void setClient(int client) {
        this.customerId = client;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }

}


