package Entities;
// Generated 18-nov-2012 18:39:09 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Sale generated by hbm2java
 */
public class Sale  implements java.io.Serializable {


     private Integer id;
     private Date date;
     private int finalProduct;
     private int price;
     private int client;
     private double total;

    public Sale() {
    }

    public Sale(Date date, int finalProduct, int price, int client, double total) {
       this.date = date;
       this.finalProduct = finalProduct;
       this.price = price;
       this.client = client;
       this.total = total;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public int getFinalProduct() {
        return this.finalProduct;
    }
    
    public void setFinalProduct(int finalProduct) {
        this.finalProduct = finalProduct;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public int getClient() {
        return this.client;
    }
    
    public void setClient(int client) {
        this.client = client;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }




}


