package Entities;
// Generated 18-nov-2012 18:39:09 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Sale generated by hbm2java
 */
public class Sale  implements java.io.Serializable {


     private Integer id;
     private Date date;
     private int customerId;
     private double total;

    public Sale() {
    }

    public Sale(Date date, int customerId, double total) {
       this.date = date;
       this.customerId = customerId;
       this.total = total;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }

}


