package Entities;
// Generated 18-nov-2012 18:39:09 by Hibernate Tools 3.2.1.GA

/**
 * Topping generated by hbm2java
 */
public class Topping implements java.io.Serializable {

    public Topping() {
        this.id = 0;
        this.name = "";
        this.price = 0;
    }

    public Topping(String name, double price) {
        this.name = name;
        this.price = price;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getPrice() {
        return this.price;
    }

    public void setPrice(double price) {
        this.price = price;
    }
    private Integer id;
    private String name;
    private double price;
}
