/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewControllers;

import Entities.DailyCashClosing;
import Helpers.MessageDisplayManager;
import Helpers.MessageType;
import Managers.DailyCashClosingManager;
import Managers.DailyCashClosingManagerImplementation;
import java.util.Iterator;
import java.util.List;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gilberto Leon <ripflame@gmail.com>
 */
public class DailyCashClosingView extends javax.swing.JFrame {

    /**
     * Creates new form DailyCashClosingView
     */
    public DailyCashClosingView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        m_dailyCashClosingButton = new javax.swing.JToggleButton();
        m_showAllButton = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        m_dailyCashClosingTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        m_dailyCashClosingButton.setText("Hacer corte de caja");
        m_dailyCashClosingButton.setFocusable(false);
        m_dailyCashClosingButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        m_dailyCashClosingButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        m_dailyCashClosingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_dailyCashClosingButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(m_dailyCashClosingButton);

        m_showAllButton.setText("Mostrar todos");
        m_showAllButton.setFocusable(false);
        m_showAllButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        m_showAllButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        m_showAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_showAllButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(m_showAllButton);

        m_dailyCashClosingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Fecha", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(m_dailyCashClosingTable);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jToolBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 376, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_showAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_showAllButtonActionPerformed
        this.searchAll();
        this.showResults();
    }//GEN-LAST:event_m_showAllButtonActionPerformed

    private void m_dailyCashClosingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_dailyCashClosingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_dailyCashClosingButtonActionPerformed

    private void makeDailyCashClosing() {
        
    }
    
    private void searchAll() {
        DailyCashClosingManager dailyCashClosingManager = new DailyCashClosingManagerImplementation();
        results = dailyCashClosingManager.getAll();
    }
    
    private void showResults() {
        DefaultTableModel model = this.createTableModel();
        if (this.results == null) {
            this.m_dailyCashClosingTable.setModel(model);
            MessageDisplayManager.showInformation(MessageType.NO_DAILY_CASH_CLOSINGS_FOUND, this);
            return;
        }
        
        String[] dailyCashClosingData = new String[3];
        Iterator<DailyCashClosing> iterator = this.results.iterator();
        while (iterator.hasNext()) {
            DailyCashClosing dailyCashClosing = iterator.next();
            dailyCashClosingData[COLUMN_ID_POSITION] = Integer.toString(dailyCashClosing.getId());
            dailyCashClosingData[COLUMN_DATE_POSITION] = dailyCashClosing.getDateEnd().toString();
            dailyCashClosingData[COLUMN_TOTAL_POSITION] = Double.toString(dailyCashClosing.getTotal());
            model.addRow(dailyCashClosingData);
        }
        this.m_dailyCashClosingTable.setModel(model);
        this.rowSelectionProperties();
    }
    
    private void rowSelectionProperties() {
        this.m_dailyCashClosingTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        this.m_dailyCashClosingTable.setCellSelectionEnabled(false);
        this.m_dailyCashClosingTable.setRowSelectionAllowed(true);
    }
    
    private DefaultTableModel createTableModel() {
        DefaultTableModel model = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        String[] columnNames = new String[3];
        columnNames[COLUMN_ID_POSITION] = ID;
        columnNames[COLUMN_DATE_POSITION] = DATE;
        columnNames[COLUMN_TOTAL_POSITION] = TOTAL;
        
        model.setColumnIdentifiers(columnNames);
        
        return model;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DailyCashClosingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DailyCashClosingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DailyCashClosingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DailyCashClosingView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DailyCashClosingView().setVisible(true);
            }
        });
    }
    
    private static final int COLUMN_ID_POSITION = 0;
    private static final int COLUMN_DATE_POSITION = 1;
    private static final int COLUMN_TOTAL_POSITION = 2;
    private static final String ID = "Id";
    private static final String DATE = "Fecha";
    private static final String TOTAL = "Total";
    
    private List<DailyCashClosing> results;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToggleButton m_dailyCashClosingButton;
    private javax.swing.JTable m_dailyCashClosingTable;
    private javax.swing.JToggleButton m_showAllButton;
    // End of variables declaration//GEN-END:variables
}
