/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewControllers;

import Entities.Sale;
import Managers.SaleManager;
import Managers.SaleManagerImplementation;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

/**
 *
 * @author Asus
 */
public class ExpenseEstatistics extends javax.swing.JFrame {

    /**
     * Creates new form ExpenseEstatistics
     */
    public ExpenseEstatistics() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_dateChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        m_searchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        m_searchButton.setText("jButton1");
        m_searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_searchButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(156, 156, 156)
                        .add(m_searchButton)
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(110, 110, 110)
                .add(m_dateChooser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 128, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(m_dateChooser, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(m_searchButton)
                .add(37, 37, 37)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 102, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void m_searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_searchButtonActionPerformed
        Date date = m_dateChooser.getDate();
        String dateString = convertCalendarDateToString(date);
        SaleManager saleManager = new SaleManagerImplementation();
        List<Sale> salesList = saleManager.getAll();
        Iterator<Sale> saleIterator = salesList.iterator();
        List<Sale> salesInDate = new ArrayList<Sale>();
        while(saleIterator.hasNext()){
            Sale currentSale = saleIterator.next();
            Date dateSale = currentSale.getDate();
            String convertUtilDateToString = convertUtilDateToString(dateSale);
            if(convertUtilDateToString.equalsIgnoreCase(dateString)){
                salesInDate.add(currentSale); 
            }
        }
        createTable(salesInDate);
    }//GEN-LAST:event_m_searchButtonActionPerformed

    private void createTable(List sales){
        
    }
    
    private String convertUtilDateToString(Date date){
        String stringDate = date.toString();
        String[] splittedString = stringDate.split(SPACE_BAR);
        String datePartOfString = splittedString[0];
        return datePartOfString;
        
    }
    
    private String convertCalendarDateToString(Date date){
        String year = String.valueOf(date.getYear() + YEAR_CONSTANT);
        String dateString = year + SPACE;
        dateString = dateString + String.valueOf(date.getMonth() + MONTH_CONVERTER) + SPACE;
        Calendar calendar = m_dateChooser.getCalendar();
        int daySelected = calendar.get(DAY_FIELD);
        if(daySelected <= FIRST_9_NUMBERS){
            dateString = dateString + ZERO + String.valueOf(daySelected);
        } else {
            dateString = dateString + String.valueOf(daySelected);
        }
        
        return dateString;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExpenseEstatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExpenseEstatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExpenseEstatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExpenseEstatistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExpenseEstatistics().setVisible(true);
            }
        });
    }
    
    
    private final static String SPACE_BAR = " ";
    private final static String ZERO = "0";
    private final static int MONTH_CONVERTER = 1;
    private final static int DAY_FIELD = 5;
    private final static int FIRST_9_NUMBERS = 9;
    private final static int YEAR_CONSTANT = 1900;
    private final static String SPACE = "-";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser m_dateChooser;
    private javax.swing.JButton m_searchButton;
    // End of variables declaration//GEN-END:variables
}
