/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewControllers;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ileana Guadalupe Ontiveros Mena
 */
public class ProductsManagement extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form ProductsView
     */
    public ProductsManagement() {
        initComponents();
        initButtonGruop();
        initManagementComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productsButtonGroup = new javax.swing.ButtonGroup();
        managementToolBar = new javax.swing.JToolBar();
        newButton = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        showAllButton = new javax.swing.JButton();
        optionsSeparator = new javax.swing.JSeparator();
        baseProductRadioButton = new javax.swing.JRadioButton();
        toppingRadioButton = new javax.swing.JRadioButton();
        otherProductRadioButton = new javax.swing.JRadioButton();
        productsScrollPane = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MonchiSoft - Gestión de Productos");
        setResizable(false);

        managementToolBar.setFloatable(false);
        managementToolBar.setRollover(true);

        newButton.setText("Nuevo");
        newButton.setFocusable(false);
        newButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        managementToolBar.add(newButton);

        modifyButton.setText("Modificar");
        modifyButton.setFocusable(false);
        modifyButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modifyButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        managementToolBar.add(modifyButton);

        removeButton.setText("Eliminar");
        removeButton.setFocusable(false);
        removeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        managementToolBar.add(removeButton);

        showAllButton.setText("Mostrar todos");
        showAllButton.setFocusable(false);
        showAllButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        showAllButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        managementToolBar.add(showAllButton);

        baseProductRadioButton.setText("Producto Base");

        toppingRadioButton.setText("Topping");

        otherProductRadioButton.setText("Otro producto");

        productsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", ""
            }
        ));
        productsScrollPane.setViewportView(productsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(managementToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(optionsSeparator)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(baseProductRadioButton)
                .addGap(18, 18, 18)
                .addComponent(toppingRadioButton)
                .addGap(18, 18, 18)
                .addComponent(otherProductRadioButton)
                .addContainerGap(107, Short.MAX_VALUE))
            .addComponent(productsScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baseProductRadioButton)
                    .addComponent(toppingRadioButton)
                    .addComponent(otherProductRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optionsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(managementToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(productsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    @Override
    public void actionPerformed(ActionEvent e) {
        
        String optionSelected = e.getActionCommand();
        
        if (optionSelected.equalsIgnoreCase(BASE_PRODUCT_COMMAND)){
            //productsTable.setModel(m_baseProductTableModel);
        } else if (optionSelected.equalsIgnoreCase(OTHER_PRODUCT_COMMAND)){
            m_baseProductManagementComponents.getModelTable();
        } else if (optionSelected.equalsIgnoreCase(TOPPING_COMMAND)){
            m_baseProductManagementComponents.getModelTable();        
        } else {JOptionPane.showMessageDialog(null,"Ha ocurrido un evento que no se ha considerado");}
   
    }

    private void initButtonGruop (){    
        baseProductRadioButton.setActionCommand(BASE_PRODUCT_COMMAND);
        toppingRadioButton.setActionCommand(OTHER_PRODUCT_COMMAND);
        otherProductRadioButton.setActionCommand(TOPPING_COMMAND);
                        
        ButtonGroup productsButtonGroup = new ButtonGroup();
        productsButtonGroup.add(baseProductRadioButton);
        productsButtonGroup.add(toppingRadioButton);
        productsButtonGroup.add(otherProductRadioButton);
        
        baseProductRadioButton.addActionListener(this);
        toppingRadioButton.addActionListener(this);
        otherProductRadioButton.addActionListener(this);
    }
    
    public void addActionsListener (ActionListener commandsListener){
        this.newButton.addActionListener(commandsListener);
        this.modifyButton.addActionListener(commandsListener);
        this.removeButton.addActionListener(commandsListener);
        this.showAllButton.addActionListener(commandsListener);
    }
    
    private void setBaseProductManagementComponents() {
        this.m_baseProductManagementComponents = new BaseProductManagementComponents();
    }
    
    private void setToppingManagementComponents() {
        this.m_toppingManagementComponents = new ToppingManagementComponents();
    }
    
    private void setOtherProductManagementComponents() {
        this.m_otherProductManagementComponents = new OtherProductManagementComponents();
    }
     
    private void initManagementComponents(){
        setBaseProductManagementComponents();
        setToppingManagementComponents();
        setOtherProductManagementComponents();
        
        m_baseProductTableModel = m_baseProductManagementComponents.getModelTable();
        productsTable.setModel(m_baseProductTableModel);

        
    }
   
    private static final String BASE_PRODUCT_COMMAND = "Base";
    private static final String OTHER_PRODUCT_COMMAND = "Otro";
    private static final String TOPPING_COMMAND = "Topping";

    private ManagementComponents m_baseProductManagementComponents;
    private ManagementComponents m_otherProductManagementComponents;
    private ManagementComponents m_toppingManagementComponents;
    private DefaultTableModel m_baseProductTableModel;
    private DefaultTableModel m_toppingTableModel;
    private DefaultTableModel m_otherProductTableModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton baseProductRadioButton;
    private javax.swing.JToolBar managementToolBar;
    private javax.swing.JButton modifyButton;
    private javax.swing.JButton newButton;
    private javax.swing.JSeparator optionsSeparator;
    private javax.swing.JRadioButton otherProductRadioButton;
    private javax.swing.ButtonGroup productsButtonGroup;
    private javax.swing.JScrollPane productsScrollPane;
    private javax.swing.JTable productsTable;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton showAllButton;
    private javax.swing.JRadioButton toppingRadioButton;
    // End of variables declaration//GEN-END:variables
}
