/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewControllers;

import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;

/**
 *
 * @author Ileana Guadalupe Ontiveros Mena
 */
public class ProductsManagement extends javax.swing.JFrame {

    /**
     * Creates new form ProductsView
     */
    public ProductsManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productsButtonGroup = new javax.swing.ButtonGroup();
        managementToolBar = new javax.swing.JToolBar();
        newButton = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        optionsSeparator = new javax.swing.JSeparator();
        baseProductRadioButton = new javax.swing.JRadioButton();
        toppingRadioButton = new javax.swing.JRadioButton();
        otherProductRadioButton = new javax.swing.JRadioButton();
        productsScrollPane = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MonchiSoft - Gestión de Productos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        managementToolBar.setFloatable(false);
        managementToolBar.setRollover(true);

        newButton.setText("Nuevo");
        newButton.setEnabled(false);
        newButton.setFocusable(false);
        newButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        managementToolBar.add(newButton);

        modifyButton.setText("Modificar");
        modifyButton.setEnabled(false);
        modifyButton.setFocusable(false);
        modifyButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modifyButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        managementToolBar.add(modifyButton);

        removeButton.setText("Eliminar");
        removeButton.setEnabled(false);
        removeButton.setFocusable(false);
        removeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        managementToolBar.add(removeButton);

        baseProductRadioButton.setText("Producto Base");

        toppingRadioButton.setText("Topping");

        otherProductRadioButton.setText("Otro producto");

        productsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", ""
            }
        ));
        productsTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                productsTableFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                productsTableFocusLost(evt);
            }
        });
        productsScrollPane.setViewportView(productsTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(managementToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(optionsSeparator)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(baseProductRadioButton)
                .addGap(18, 18, 18)
                .addComponent(toppingRadioButton)
                .addGap(18, 18, 18)
                .addComponent(otherProductRadioButton)
                .addContainerGap(107, Short.MAX_VALUE))
            .addComponent(productsScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baseProductRadioButton)
                    .addComponent(toppingRadioButton)
                    .addComponent(otherProductRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optionsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(managementToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(productsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        AdministratorView administratorView = new AdministratorView();
        administratorView.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_formWindowClosed

    private void productsTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productsTableFocusGained
        enableModifyButton ();
        enableRemoveButton ();
    }//GEN-LAST:event_productsTableFocusGained

    private void productsTableFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_productsTableFocusLost
        disableModifyButton ();
        disableRemoveButton ();
    }//GEN-LAST:event_productsTableFocusLost

    public void addActionsListener (ActionListener commandsListener){
        this.newButton.addActionListener(commandsListener);
        this.modifyButton.addActionListener(commandsListener);
        this.removeButton.addActionListener(commandsListener);
    }
    
    public void removeActionsListener (ActionListener commandsListener){
        this.newButton.removeActionListener(commandsListener);
        this.modifyButton.removeActionListener(commandsListener);
        this.removeButton.removeActionListener(commandsListener);
    }
    
    public void disableNewButton (){
        this.newButton.setEnabled(false);
    }
    
    public void disableModifyButton (){
        this.modifyButton.setEnabled(false);
    }
    
    public void disableRemoveButton (){
        this.removeButton.setEnabled(false);
    }
    
    public void enableNewButton (){
        this.newButton.setEnabled(true);
    }
    
    public void enableModifyButton (){
        this.modifyButton.setEnabled(true);
    }
    
    public void enableRemoveButton (){
        this.removeButton.setEnabled(true);
    }
    
    public void initButtonGroup (){                           
        ButtonGroup productsButtonGroup = new ButtonGroup();
        productsButtonGroup.add(baseProductRadioButton);
        productsButtonGroup.add(toppingRadioButton);
        productsButtonGroup.add(otherProductRadioButton);   
    }
    
    public void addButtonGroupListener(ActionListener choiceListener){
        this.baseProductRadioButton.addActionListener(choiceListener);
        this.toppingRadioButton.addActionListener(choiceListener);
        this.otherProductRadioButton.addActionListener(choiceListener);
    }
    
    
    public String getTextCell (){
    
        return "";
    }
    
    public CaptureProductData m_captureProductData;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton baseProductRadioButton;
    private javax.swing.JToolBar managementToolBar;
    private javax.swing.JButton modifyButton;
    public javax.swing.JButton newButton;
    private javax.swing.JSeparator optionsSeparator;
    public javax.swing.JRadioButton otherProductRadioButton;
    private javax.swing.ButtonGroup productsButtonGroup;
    private javax.swing.JScrollPane productsScrollPane;
    public javax.swing.JTable productsTable;
    private javax.swing.JButton removeButton;
    public javax.swing.JRadioButton toppingRadioButton;
    // End of variables declaration//GEN-END:variables

}
