/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewControllers;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Ileana Guadalupe Ontiveros Mena
 */
public class ProductsManagementView extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form ProductsView
     */
    public ProductsManagementView() {
        initComponents();
        
        baseProductRadioButton.setActionCommand("Hola");
        toppingRadioButton.setActionCommand("1");
        otherProductRadioButton.setActionCommand("2");
        
        toppingRadioButton.addActionListener(this);
        otherProductRadioButton.addActionListener(this);
        
        
        ButtonGroup productsbuttonGroup = new ButtonGroup();
        productsbuttonGroup.add(baseProductRadioButton);
        productsbuttonGroup.add(toppingRadioButton);
        productsbuttonGroup.add(otherProductRadioButton);
        
        baseProductRadioButton.addActionListener(this);
        toppingRadioButton.addActionListener(this);
        otherProductRadioButton.addActionListener(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productsButtonGroup = new javax.swing.ButtonGroup();
        managementToolBar = new javax.swing.JToolBar();
        newButton = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        showAllButton = new javax.swing.JButton();
        optionsSeparator = new javax.swing.JSeparator();
        baseProductRadioButton = new javax.swing.JRadioButton();
        toppingRadioButton = new javax.swing.JRadioButton();
        otherProductRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MonchiSoft - Gestión de Productos");

        managementToolBar.setFloatable(false);
        managementToolBar.setRollover(true);

        newButton.setText("Nuevo");
        newButton.setFocusable(false);
        newButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        managementToolBar.add(newButton);

        modifyButton.setText("Modificar");
        modifyButton.setFocusable(false);
        modifyButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modifyButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        managementToolBar.add(modifyButton);

        removeButton.setText("Eliminar");
        removeButton.setFocusable(false);
        removeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        removeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        managementToolBar.add(removeButton);

        showAllButton.setText("Mostrar todos");
        showAllButton.setFocusable(false);
        showAllButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        showAllButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        managementToolBar.add(showAllButton);

        baseProductRadioButton.setText("Producto Base");

        toppingRadioButton.setText("Topping");

        otherProductRadioButton.setText("Otro producto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(managementToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(optionsSeparator)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(baseProductRadioButton)
                .addGap(18, 18, 18)
                .addComponent(toppingRadioButton)
                .addGap(18, 18, 18)
                .addComponent(otherProductRadioButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baseProductRadioButton)
                    .addComponent(toppingRadioButton)
                    .addComponent(otherProductRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optionsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(managementToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductsManagementView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductsManagementView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductsManagementView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductsManagementView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ProductsManagementView().setVisible(true);
            }
        });
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        
        String comando = e.getActionCommand();
        if (comando.equalsIgnoreCase("Hola")){
           JOptionPane.showMessageDialog(null,"Hola");
        }
        else {JOptionPane.showMessageDialog(null,"Ileana");}
   
}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton baseProductRadioButton;
    private javax.swing.JToolBar managementToolBar;
    private javax.swing.JButton modifyButton;
    private javax.swing.JButton newButton;
    private javax.swing.JSeparator optionsSeparator;
    private javax.swing.JRadioButton otherProductRadioButton;
    private javax.swing.ButtonGroup productsButtonGroup;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton showAllButton;
    private javax.swing.JRadioButton toppingRadioButton;
    // End of variables declaration//GEN-END:variables
}
