/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewControllers;

import Entities.*;
import Helpers.MessageDisplayManger;
import Helpers.MessageType;
import Managers.*;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bzeheatnix
 */
public class StatisticsView extends javax.swing.JFrame {

    private int COLUMN_NAME_POSITION = 0;
    private int COLUMN_QUANTITY_POSITION = 0;
    private String NAME = "Nombre";
    private String QUANTITY = "Cantidad";

    /**
     * Creates new form StatisticsView
     */
    public StatisticsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_dateField = new com.toedter.calendar.JDateChooser();
        m_basesListButton = new javax.swing.JButton();
        m_toppingsListButton = new javax.swing.JButton();
        m_othersListButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        m_statisticsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Estadísticas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        m_basesListButton.setText("Bases");
        m_basesListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_basesListButtonActionPerformed(evt);
            }
        });

        m_toppingsListButton.setText("Toppings");

        m_othersListButton.setText("Otros");

        m_statisticsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(m_statisticsTable);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(113, 113, 113)
                        .add(m_basesListButton)
                        .add(45, 45, 45)
                        .add(m_toppingsListButton)
                        .add(44, 44, 44)
                        .add(m_othersListButton))
                    .add(layout.createSequentialGroup()
                        .add(204, 204, 204)
                        .add(m_dateField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(56, 56, 56)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 454, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(42, 42, 42)
                .add(m_dateField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(28, 28, 28)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(m_basesListButton)
                    .add(m_toppingsListButton)
                    .add(m_othersListButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 341, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        AdministratorView administratorView = new AdministratorView();
        administratorView.setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void m_basesListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_basesListButtonActionPerformed
        showAllBaseProducts();
    }//GEN-LAST:event_m_basesListButtonActionPerformed

    private DefaultTableModel createTableModel() {
        DefaultTableModel model = new DefaultTableModel() {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        String[] columnNames = new String[2];
        columnNames[COLUMN_NAME_POSITION] = NAME;
        columnNames[COLUMN_QUANTITY_POSITION] = QUANTITY;

        model.setColumnIdentifiers(columnNames);

        return model;
    }
    
    public List<Sale> getAllDaySales(Date date) {
        SaleManager saleManager = new SaleManagerImplementation();
        List<Sale> sales = saleManager.getAll();
        
        return sales;
    }

    public void showAllBaseProducts() {
        List<Sale> daySales = getAllDaySales(this.m_dateField.getDate());;
        DefaultTableModel model = this.createTableModel();
        if (daySales == null) {
            this.m_statisticsTable.setModel(model);
//            MessageDisplayManger.showInformation(MessageType.NO_SALES_FOUND, this);
            return;
        }
        
        int quantity = 0;
        
        String[] customerData = new String[2];
        Iterator<Sale> saleIterator = daySales.iterator();
        while (saleIterator.hasNext()) {
            Sale sale = saleIterator.next();
            SaleFinalProductsManager saleFinalProductManager = new SaleFinalProductsManagerImplementation();
            
            List<SaleFinalProducts> finalProductsList = saleFinalProductManager.searchById(sale.getId());
            Iterator<SaleFinalProducts> saleFinalProductIterator = finalProductsList.iterator();
            while (saleFinalProductIterator.hasNext()) {
                SaleFinalProducts saleFinalProduct = saleFinalProductIterator.next();
                SaleFinalProductsId saleFinalProductId = saleFinalProduct.getId();
                FinalProductManager finalProductManager = new FinalProductManagerImplementation();
                List<FinalProduct> finalProductFound = finalProductManager.searchById(saleFinalProductId.getFinalProductsId());
                FinalProduct finalProduct = finalProductFound.get(0);
                int baseProductId = finalProduct.getBaseProduct();
                BaseProductManager baseProductManager = new BaseProductManagerImplementation();
                List<BaseProduct> baseProductFound = baseProductManager.searchById(baseProductId);
                BaseProduct baseProduct = baseProductFound.get(0);
                customerData[COLUMN_NAME_POSITION] =  baseProduct.getName();
//                customerData[COLUMN_QUANTITY_POSITION] = getBaseProductQuantity(baseProduct);
                
            }
                
           model.addRow(customerData);
        }
        this.m_statisticsTable.setModel(model);
//        this.rowSelectionProperties();
    }
//    
//    private int getBaseProductQuantity(BaseProduct product) {
//        SaleManager saleManager = new SaleManagerImplementation();
//        List<Sale> sales = saleManager.getAll();
//        int visitsNumber = 0;
//
//        Iterator<Sale> iterator = sales.iterator();
//        while (iterator.hasNext()) {
//            Sale sale = iterator.next();
//            if (sale.getCustomerId() == customer.getId()) {
//                visitsNumber++;
//            }
//
//        }
//
//        return visitsNumber;
//    }

    public void showAllToppings() {
        
    }

    public void showAllOtherProducts() {
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatisticsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatisticsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatisticsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatisticsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new StatisticsView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton m_basesListButton;
    private com.toedter.calendar.JDateChooser m_dateField;
    private javax.swing.JButton m_othersListButton;
    private javax.swing.JTable m_statisticsTable;
    private javax.swing.JButton m_toppingsListButton;
    // End of variables declaration//GEN-END:variables
}
